### ISSUE TITLE
cwd() and getcwd() don't return logical path

### ISSUE THREAD

**Issue by cfaber** [jkeenan/PathTools#1]
I've discovered that Cwd::cwd() doesn't return a logical path on Linux POSIX ext4 or zfs file systems

$ cd /tmp
$ mkdir x
$ ln -s x y
$ cd y
$ ls -l1 /tmp | grep -v total ; perl -MCwd -e 'print Cwd::getcwd() . "\n"' ; pwd -L ; pwd
drwxr-xr-x 2 cfaber cfaber 4096 Jan 21 16:37 x
lrwxrwxrwx 1 cfaber cfaber    1 Jan 21 16:37 y -> x
/tmp/x
/tmp/y
/tmp/y

this is present on Debian 3.2.96-2 x86_64 GNU/Linux with perl v5.14.2 built for x86_64-linux-gnu-thread-multi

and 

#70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux with perl v5.30.0 built for x86_64-linux-gnu-thread-multi

**Comment by cfaber** [comment]
It seems, that there's something strange with how perl changes directories which causes the logical path to be lost:

$ cd /tmp/y ; perl -e 'print \`pwd -L\`';
/tmp/y
$ cd /tmp ; perl -e 'chdir("y"); print \`pwd -L\`';
/tmp/x

**Comment by cfaber** [comment]
ahha, https://github.com/wertarbyte/coreutils/blob/master/src/pwd.c#L298

So that explains that, but how about logical paths with Cwd??

**Comment by jkeenan** [comment]
This is not the best place to report this problem.  At some point in the past, I extracted the PathTools code out of the Perl 5 core distribution in order to do some work on it.  But I am not the maintainer of this module.  This module is maintained as part of the Perl 5 core distribution by the Perl 5 Porters.  So please file this bug report at: https://github.com/Perl/perl5/issues
